// <auto-generated />
using System;
using Disney_Proyect_Akemy.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Disney_Proyect_Akemy.Migrations
{
    [DbContext(typeof(PersonajesDataBaseContext))]
    [Migration("20221014212647_InitDB")]
    partial class InitDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Disney_Proyect_Akemy.Models.Peliculas", b =>
                {
                    b.Property<int>("PeliculasId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Calificacion")
                        .HasColumnType("int");

                    b.Property<int>("Creacion")
                        .HasColumnType("int");

                    b.Property<int?>("PersonajesId")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PeliculasId");

                    b.HasIndex("PersonajesId");

                    b.ToTable("Peliculas");
                });

            modelBuilder.Entity("Disney_Proyect_Akemy.Models.Personajes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<string>("Historia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Peso")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Personajes");
                });

            modelBuilder.Entity("Disney_Proyect_Akemy.Models.PersonajesPorPeliculas", b =>
                {
                    b.Property<int?>("PeliculasId")
                        .HasColumnType("int");

                    b.Property<int?>("PersonajesId")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("PeliculasId", "PersonajesId");

                    b.HasIndex("PersonajesId");

                    b.ToTable("PersonajesPorPeliculas");
                });

            modelBuilder.Entity("Disney_Proyect_Akemy.Models.PersonajesPorSeries", b =>
                {
                    b.Property<int?>("SeriesId")
                        .HasColumnType("int");

                    b.Property<int?>("PersonajesId")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("SeriesId", "PersonajesId");

                    b.HasIndex("PersonajesId");

                    b.ToTable("PersonajesPorSeries");
                });

            modelBuilder.Entity("Disney_Proyect_Akemy.Models.Series", b =>
                {
                    b.Property<int>("SeriesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Calificacion")
                        .HasColumnType("int");

                    b.Property<int>("Creacion")
                        .HasColumnType("int");

                    b.Property<int?>("PersonajesId")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SeriesId");

                    b.HasIndex("PersonajesId");

                    b.ToTable("Series");
                });

            modelBuilder.Entity("Disney_Proyect_Akemy.Models.Peliculas", b =>
                {
                    b.HasOne("Disney_Proyect_Akemy.Models.Personajes", "Personajes")
                        .WithMany("Peliculas")
                        .HasForeignKey("PersonajesId");
                });

            modelBuilder.Entity("Disney_Proyect_Akemy.Models.PersonajesPorPeliculas", b =>
                {
                    b.HasOne("Disney_Proyect_Akemy.Models.Peliculas", "Peliculas")
                        .WithMany()
                        .HasForeignKey("PeliculasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Disney_Proyect_Akemy.Models.Personajes", "Personajes")
                        .WithMany()
                        .HasForeignKey("PersonajesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Disney_Proyect_Akemy.Models.PersonajesPorSeries", b =>
                {
                    b.HasOne("Disney_Proyect_Akemy.Models.Personajes", "Personajes")
                        .WithMany()
                        .HasForeignKey("PersonajesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Disney_Proyect_Akemy.Models.Series", "Series")
                        .WithMany()
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Disney_Proyect_Akemy.Models.Series", b =>
                {
                    b.HasOne("Disney_Proyect_Akemy.Models.Personajes", "Personajes")
                        .WithMany("Series")
                        .HasForeignKey("PersonajesId");
                });
#pragma warning restore 612, 618
        }
    }
}
